# Generated by Django 6.0.2 on 2026-03-23 03:43

from django.db import migrations


def set_superadmin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='bkmoonsalter@gmail.com').update(is_superadmin=True)


def unset_superadmin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='bkmoonsalter@gmail.com').update(is_superadmin=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_superadmin_loginattempt_registereddevice'),
    ]

    operations = [
        migrations.RunPython(set_superadmin, unset_superadmin),
    ]
