# Generated by Django 6.0.2 on 2026-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('payment_received', 'Payment Received'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('review_approved', 'Review Approved'), ('system', 'System Message'), ('pending_payment_review', 'Pending Payment Review'), ('new_booking', 'New Booking'), ('new_review_pending', 'New Review Pending')], max_length=30),
        ),
    ]
