# Generated by Django 6.0.2 on 2026-04-13 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('payment_received', 'Payment Received'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('review_approved', 'Review Approved'), ('system', 'System Message'), ('pending_payment_review', 'Pending Payment Review'), ('new_booking', 'New Booking'), ('new_review_pending', 'New Review Pending'), ('new_message', 'New Message')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-()]{7,20}$', 'Enter a valid phone number.')]),
        ),
    ]
