# Generated by Django 6.0.2 on 2026-04-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_notification_type'),
        ('accounts', '0009_alter_notification_notification_type_and_more'),
    ]

    operations = [
    ]
