# Generated by Django 6.0.2 on 2026-04-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('room', 'Room'), ('content', 'Content'), ('user', 'User Management'), ('review', 'Review'), ('voucher', 'Voucher'), ('settings', 'Settings'), ('auth', 'Authentication'), ('payroll', 'Payroll'), ('loan', 'Loan')], max_length=20),
        ),
    ]
