# Generated by Django 6.0.2 on 2026-04-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260413_2124'),
        ('accounts', '0010_user_is_admin_alter_activitylog_category'),
    ]

    operations = [
    ]
