# Generated by Django 6.0.2 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_admin_alter_activitylog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bypass_device_authorization',
            field=models.BooleanField(default=False),
        ),
    ]
