# Generated by Django 5.0.6 on 2026-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour_type',
            field=models.CharField(choices=[('day', 'Day Tour (8AM – 5PM)'), ('night', 'Night Tour (5PM – 8AM)')], default='day', max_length=10),
        ),
    ]
