# Generated by Django 6.0.2 on 2026-02-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_tour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_intent_id',
        ),
    ]
