# Generated by Django 6.0.2 on 2026-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
