# Generated by Django 6.0.2 on 2026-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_backdated',
            field=models.BooleanField(default=False),
        ),
    ]
