# Generated by Django 6.0.2 on 2026-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_is_backdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
