# Generated by Django 6.0.2 on 2026-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_excluded_from_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_discount_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
