# Generated by Django 6.0.2 on 2026-02-28 19:01

from django.db import migrations, models


def merge_room_types(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    mapping = {
        'small_cottage': 'cottage',
        'large_cottage': 'cottage',
        'dos_andanas_down': 'dos_andanas',
        'dos_andanas_up': 'dos_andanas',
        'dos_andanas_room_sm': 'dos_andanas',
        'dos_andanas_room_lg': 'dos_andanas',
        'kubo_with_toilet': 'kubo',
        'kubo_without_toilet': 'kubo',
    }
    for old_type, new_type in mapping.items():
        Room.objects.filter(room_type=old_type).update(room_type=new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_dual_pricing'),
    ]

    operations = [
        migrations.RunPython(merge_room_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('dos_andanas', 'Dos Andanas'), ('lavender_house', 'Lavender House'), ('ac_karaoke', 'Air-Conditioned Karaoke Room'), ('kubo', 'Kubo'), ('function_hall', 'Function Hall'), ('trapal_table', 'Trapal Table')], default='cottage', max_length=25),
        ),
    ]
