# Generated by Django 6.0.2 on 2026-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_max_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_mode',
            field=models.CharField(choices=[('slot', 'Day/Night Slot'), ('overnight', 'Overnight (Check-in 2PM / Check-out 12NN)')], default='slot', max_length=15),
        ),
    ]
