# Generated by Django 6.0.2 on 2026-04-09 10:48

from django.db import migrations


def set_overnight_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    # These room types use overnight check-in 2PM / check-out 12NN
    overnight_types = ['kubo', 'dos_andanas', 'lavender_house', 'ac_karaoke']
    Room.objects.filter(room_type__in=overnight_types).update(booking_mode='overnight')


def reverse(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Room.objects.all().update(booking_mode='slot')


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_add_booking_mode'),
    ]

    operations = [
        migrations.RunPython(set_overnight_rooms, reverse),
    ]
