# Generated by Django 6.0.2 on 2026-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_set_overnight_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking_mode',
            field=models.CharField(choices=[('slot', 'Day/Night Slot'), ('overnight', 'Overnight (Check-in 2PM / Check-out 12NN)'), ('24hr', '24-Hour (Check-in & Check-out same time next day)')], default='slot', max_length=15),
        ),
    ]
