# Generated by Django 6.0.2 on 2026-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_booking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('dos_andanas', 'Dos Andanas'), ('lavender_house', 'Lavender House'), ('ac_karaoke', 'Air-Conditioned Room'), ('kubo', 'Kubo'), ('function_hall', 'Function Hall'), ('trapal_table', 'Trapal Table')], default='cottage', max_length=25),
        ),
    ]
