# Generated by Django 6.0.2 on 2026-04-16 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagIbigRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True)),
                ('ee_rate_low_percent', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ee_rate_high_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('er_rate_percent', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('msc_ceiling', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('low_high_threshold', models.DecimalField(decimal_places=2, default=1500, max_digits=12)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PhilHealthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True)),
                ('premium_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary_floor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_ceiling', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='BIRTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('semi_monthly', 'Semi-monthly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=14)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate_on_excess_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('excess_over', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-effective_from', 'period', 'range_from'],
                'constraints': [models.UniqueConstraint(fields=('effective_from', 'period', 'range_from'), name='unique_bir_bracket_per_effective_period')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('sss_number', models.CharField(blank=True, max_length=20)),
                ('philhealth_number', models.CharField(blank=True, max_length=20)),
                ('pagibig_number', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('regular', 'Regular'), ('probationary', 'Probationary'), ('contractual', 'Contractual'), ('part_time', 'Part-time')], default='regular', max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='CompensationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('monthly_basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_schedule', models.CharField(choices=[('semi_monthly', 'Semi-monthly (15th & EOM)'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=20)),
                ('weekly_cutoff_day', models.PositiveSmallIntegerField(blank=True, help_text='1=Mon, 7=Sun. Required when pay_schedule=WEEKLY.', null=True)),
                ('weekly_basis', models.DecimalField(blank=True, decimal_places=2, help_text='Optional flat weekly gross. If null, derived from monthly_basic_salary x 12 / 52.', max_digits=12, null=True)),
                ('sss_msc_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_status', models.CharField(choices=[('single', 'Single'), ('head_of_family', 'Head of Family'), ('married', 'Married')], default='single', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_method', models.CharField(choices=[('none', 'No Interest'), ('simple', 'Simple'), ('diminishing', 'Diminishing')], default='none', max_length=20)),
                ('term_periods', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('auto_deduct', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half', models.CharField(choices=[('first_half', '1st-15th'), ('second_half', '16th-EOM'), ('whole_month', 'Whole Month'), ('week', 'Week'), ('thirteenth_month', '13th Month')], max_length=20)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cutoff_day', models.PositiveSmallIntegerField(blank=True, help_text='Weekday the WEEK period ends (1=Mon..7=Sun). Only set when half=WEEK.', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['year', 'month', 'half', 'week_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('week_number__isnull', True)), fields=('year', 'month', 'half'), name='unique_period_year_month_half'), models.UniqueConstraint(condition=models.Q(('week_number__isnull', False)), fields=('year', 'half', 'week_number', 'cutoff_day'), name='unique_period_week')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_finalized', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='hr.payrollperiod')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('days_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gross_basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('night_diff', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances_non_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sss_ee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('philhealth_ee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagibig_ee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deduction_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sss_er', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('philhealth_er', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagibig_er', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ec_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('compensation_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.compensationprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('source', models.CharField(choices=[('payroll_deduction', 'Payroll Deduction'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('gcash', 'GCash'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.loan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='hr.payslip')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution'), ('info', 'Info')], max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hr.payslip')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SSSBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ee_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('er_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ec_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
            ],
            options={
                'ordering': ['-effective_from', 'range_from'],
                'constraints': [models.UniqueConstraint(fields=('range_from', 'effective_from'), name='unique_sss_bracket_per_effective')],
            },
        ),
        migrations.AddConstraint(
            model_name='compensationprofile',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_date'), name='unique_compensation_per_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('period',), name='one_live_run_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='unique_payslip_per_run_employee'),
        ),
    ]
