# Generated by Django 6.0.2 on 2026-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
