# Generated by Django 6.0.2 on 2026-04-17 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_loan_payment_is_voided'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True)),
                ('ot_ordinary_pct', models.DecimalField(decimal_places=2, default=125.0, help_text='Overtime on ordinary workday (% of hourly rate)', max_digits=5)),
                ('ot_rest_day_pct', models.DecimalField(decimal_places=2, default=160.0, help_text='Overtime on rest day (% of hourly rate)', max_digits=5)),
                ('ot_regular_holiday_pct', models.DecimalField(decimal_places=2, default=260.0, help_text='Overtime on regular holiday (% of hourly rate)', max_digits=5)),
                ('ot_special_holiday_pct', models.DecimalField(decimal_places=2, default=195.0, help_text='Overtime on special non-working holiday (% of hourly rate)', max_digits=5)),
                ('ot_rest_day_regular_holiday_pct', models.DecimalField(decimal_places=2, default=390.0, help_text='Overtime on rest day + regular holiday (% of hourly rate)', max_digits=5)),
                ('ot_rest_day_special_holiday_pct', models.DecimalField(decimal_places=2, default=195.0, help_text='Overtime on rest day + special holiday (% of hourly rate)', max_digits=5)),
                ('regular_holiday_rate_pct', models.DecimalField(decimal_places=2, default=200.0, help_text='Regular holiday first 8h (% of daily rate)', max_digits=5)),
                ('special_holiday_rate_pct', models.DecimalField(decimal_places=2, default=130.0, help_text='Special non-working holiday first 8h (% of daily rate)', max_digits=5)),
                ('rest_day_rate_pct', models.DecimalField(decimal_places=2, default=130.0, help_text='Rest day first 8h (% of daily rate)', max_digits=5)),
                ('rest_day_regular_holiday_rate_pct', models.DecimalField(decimal_places=2, default=260.0, help_text='Rest day + regular holiday first 8h (% of daily rate)', max_digits=5)),
                ('rest_day_special_holiday_rate_pct', models.DecimalField(decimal_places=2, default=150.0, help_text='Rest day + special holiday first 8h (% of daily rate)', max_digits=5)),
                ('night_diff_ordinary_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Night diff on ordinary workday (% premium on hourly rate, 10PM-6AM)', max_digits=5)),
                ('night_diff_rest_day_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Night diff on rest day (% premium on hourly rate)', max_digits=5)),
                ('night_diff_holiday_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Night diff on holiday (% premium on hourly rate)', max_digits=5)),
                ('late_deduction_multiplier_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='Late deduction multiplier (% of proportional hourly deduction)', max_digits=5)),
                ('undertime_deduction_multiplier_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='Undertime deduction multiplier (% of proportional hourly deduction)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrate_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
