# Generated by Django 6.0.2 on 2026-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payrate_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('holiday_type', models.CharField(choices=[('regular', 'Regular Holiday'), ('special_non_working', 'Special Non-Working Holiday'), ('special_working', 'Special Working Holiday')], default='regular', max_length=30)),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year on the same month/day.')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
