# Generated by Django 6.0.2 on 2026-04-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('night_diff_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('is_undertime', models.BooleanField(default=False)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('special_non_working', 'Special Non-Working')], max_length=30)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('web_clock', 'Web Clock-In'), ('manual', 'Manual Entry'), ('bulk_import', 'Bulk Import')], default='web_clock', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.shift')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time_in'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_attendan_employe_0dcc0e_idx'), models.Index(fields=['is_approved'], name='hr_attendan_is_appr_7864b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_date')],
            },
        ),
    ]
