# Generated by Django 6.0.2 on 2026-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='rest_day_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
