# Generated by Django 6.0.2 on 2026-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='hero/')),
                ('poster', models.ImageField(blank=True, upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Configuration',
                'verbose_name_plural': 'Hero Configuration',
            },
        ),
    ]
