# Generated by Django 6.0.2 on 2026-03-23 07:07

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_heroconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroconfig',
            options={'verbose_name': 'Homepage Intro', 'verbose_name_plural': 'Homepage Intro'},
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='video',
            field=models.FileField(blank=True, storage=content.models._get_video_storage, upload_to='hero/'),
        ),
    ]
