# Generated by Django 6.0.2 on 2026-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_subscriber_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='room_type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('dos_andanas', 'Dos Andanas'), ('lavender_house', 'Lavender House'), ('ac_karaoke', 'Air-Conditioned Room'), ('kubo', 'Kubo'), ('function_hall', 'Function Hall'), ('trapal_table', 'Trapal Table')], max_length=25),
        ),
    ]
