# Generated by Django 6.0.2 on 2026-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_featured_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_info',
        ),
        migrations.AddField(
            model_name='promotion',
            name='allows_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='room_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='promotion',
            name='schedule_type',
            field=models.CharField(choices=[('duration', 'Date Range'), ('recurring', 'Recurring (Weekly)'), ('permanent', 'Permanent')], default='duration', max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
