# Generated by Django 6.0.2 on 2026-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_redesign_promotion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='weekend_walkin_only',
            field=models.BooleanField(default=False, help_text='Disable online booking on weekends for cottages, trapal tables, and dos andanas'),
        ),
    ]
