# Generated by Django 6.0.2 on 2026-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_weekend_walkin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='room_type',
            field=models.CharField(choices=[('cottage', 'Cottage'), ('dos_andanas', 'Dos Andanas'), ('lavender_house', 'Lavender House'), ('ac_karaoke', 'Air-Conditioned'), ('kubo', 'Kubo'), ('function_hall', 'Function Hall'), ('trapal_table', 'Trapal Table')], max_length=25),
        ),
    ]
