[program:gunicorn]
directory=/home/adel/adel-beach-resort/backend
command=/home/adel/adel-beach-resort/backend/venv/bin/gunicorn hotel.wsgi:application --bind 127.0.0.1:8000 --workers 2 --timeout 120
user=adel
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/gunicorn/access.log
stderr_logfile=/var/log/gunicorn/error.log
environment=
    DJANGO_SETTINGS_MODULE="hotel.settings",
    PATH="/home/adel/adel-beach-resort/backend/venv/bin:%(ENV_PATH)s"
