# Generated by Django 6.0.2 on 2026-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='gcash_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='php', max_length=3),
        ),
    ]
