# Generated by Django 6.0.2 on 2026-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('downpayment', '20% Downpayment')], default='full', max_length=20),
        ),
    ]
