# Generated by Django 6.0.2 on 2026-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcash_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(upload_to='gcash/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GCash Configuration',
                'verbose_name_plural': 'GCash Configuration',
            },
        ),
    ]
