# Generated by Django 6.0.2 on 2026-03-23 06:16

import shutil
import os
from django.db import migrations
from django.conf import settings


def seed_gcash(apps, schema_editor):
    GCashConfig = apps.get_model('payments', 'GCashConfig')
    if not GCashConfig.objects.exists():
        # Copy existing QR code from static to media
        src = os.path.join(settings.BASE_DIR, '..', 'frontend', 'public', 'gcash-qr.png')
        dest_dir = os.path.join(settings.MEDIA_ROOT, 'gcash')
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, 'gcash-qr.png')
        if os.path.exists(src) and not os.path.exists(dest):
            shutil.copy2(src, dest)
        GCashConfig.objects.create(
            pk=1,
            gcash_number='0916 315 2117',
            account_name='Ralph Arcos',
            qr_code='gcash/gcash-qr.png' if os.path.exists(dest) else '',
        )


def unseed_gcash(apps, schema_editor):
    GCashConfig = apps.get_model('payments', 'GCashConfig')
    GCashConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_gcashconfig'),
    ]

    operations = [
        migrations.RunPython(seed_gcash, unseed_gcash),
    ]
