# Generated by Django 6.0.2 on 2026-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_seed_gcash_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('downpayment', '20% Downpayment'), ('partial', 'Partial Payment')], default='full', max_length=20),
        ),
    ]
