# Generated by Django 6.0.2 on 2026-05-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
